# Generated by Django 5.1.7 on 2025-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_block_name_alter_task_inquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
