# Generated by Django 5.1.7 on 2025-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
