# Generated by Django 5.1.7 on 2025-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('accepted', '승인'), ('rejected', '반려'), ('cancled', '취소')], default='pending', max_length=150),
        ),
    ]
