# Generated by Django 5.1.7 on 2025-04-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('대기', '대기'), ('승인', '승인'), ('반려', '반려'), ('취소', '취소')], default='대기', max_length=150),
        ),
    ]
